### ISSUE TITLE
Please clarify license contradiction 

### ISSUE THREAD

**Issue by lbmn** [OpenSystemsLab/jsmn.nim#1]
A [source code comment](https://github.com/OpenSystemsLab/jsmn.nim/blob/master/jsmn.nim#L10) says it's Apache-licensed, but the LICENSE and .nimble file say "MIT".  I hope it's actually MIT licensed, and the Apache comments (which are unnecessary in any case) will be removed.

**Comment by ba0f3** [comment]
fixed, thank you for interesting!
